# fly.toml app configuration file generated for ecommerce-chingu-backend on 2025-03-13T21:49:14+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ecommerce-chingu-backend'
primary_region = 'ams'

[build]
[env]
  PORT = "3000" # add this
  
[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
