POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "firstname": "Riry",
  "lastname": "Nomenjanahary",
  "email": "wellaemeraude@gmail.com",
  "password": "securepassword"
}
