
@cookie = token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RmMjQ0ZmY4N2I0NjJkNjA3ZTUxNDIiLCJpc1ZlcmlmaWVkIjpmYWxzZSwiaWF0IjoxNzQ0NDc4NDYzLCJleHAiOjE3NDUwODMyNjN9.ZrKGB5MJRvdwDD2XYLdiN5OKeIuK7hrTVSjotUPyaVc; Max-Age=604800; Path=/; Expires=Sat, 19 Apr 2025 17:21:03 GMT; HttpOnly; SameSite=Lax
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstname": "bob",
    "lastname": "beb",
    "email": "test@gmail.com",
    "password": "test"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "lol@gmail.com",
    "password": "test"
}

###
GET http://localhost:3000/api/auth/me
Content-Type: application/json
Cookie: {{cookie}}
###
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Cookie: {{cookie}}