
@cookie = access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2RmMjQ0ZmY4N2I0NjJkNjA3ZTUxNDIiLCJpYXQiOjE3NDI2NzcwNzEsImV4cCI6MTc0MzI4MTg3MX0.nlUaWHirmFLGpr6SU6Y3EHAv8_rm1JyuplvvInkORL8; Max-Age=604800; Path=/; Expires=Sat, 29 Mar 2025 20:57:51 GMT; HttpOnly; SameSite=None
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "firstname": "bob",
    "lastname": "beb",
    "email": "lol@gmail.com",
    "password": "test"
}
###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email": "lol@gmail.com",
    "password": "test"
}

###
GET http://localhost:3000/api/auth/me
Content-Type: application/json
Cookie: {cookie}